name: Test

on:
    push:
        branches: [ development, master ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ 7.3, 7.4 ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@2.12.0
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2
            -   name: Install dependencies
                run: composer update
            -   name: Run test suite
                run: composer test
